/*
    AUTO-GENERATED BOX2D INTERNAL WRAPPER FUNCTIONS
    This file is automatically generated by gen_csharp.py
    DO NOT EDIT MANUALLY

    WebAssembly/Emscripten cannot marshal structs returned by value through P/Invoke.
    These _internal helper functions work around this limitation by taking an output
    pointer parameter instead.
*/

#ifndef BOX2D_CSHARP_INTERNAL_WRAPPERS_H
#define BOX2D_CSHARP_INTERNAL_WRAPPERS_H

#include <box2d/box2d.h>
#include <box2d/math_functions.h>

// For Emscripten builds, these functions need to be exported
#ifdef __EMSCRIPTEN__
    #include <emscripten.h>
    #define BOX2D_EXPORT EMSCRIPTEN_KEEPALIVE
#else
    #define BOX2D_EXPORT
#endif

// ========== Box2D (b2) ===========

BOX2D_EXPORT void b2GetVersion_internal(b2Version* result) {
    *result = b2GetVersion();
}

BOX2D_EXPORT void b2ComputeCosSin_internal(b2CosSin* result, float radians) {
    *result = b2ComputeCosSin(radians);
}

BOX2D_EXPORT void b2ComputeRotationBetweenUnitVectors_internal(b2Rot* result, b2Vec2 v1, b2Vec2 v2) {
    *result = b2ComputeRotationBetweenUnitVectors(v1, v2);
}

BOX2D_EXPORT void b2MakePolygon_internal(b2Polygon* result, const b2Hull * hull, float radius) {
    *result = b2MakePolygon(hull, radius);
}

BOX2D_EXPORT void b2MakeOffsetPolygon_internal(b2Polygon* result, const b2Hull * hull, b2Vec2 position, b2Rot rotation) {
    *result = b2MakeOffsetPolygon(hull, position, rotation);
}

BOX2D_EXPORT void b2MakeOffsetRoundedPolygon_internal(b2Polygon* result, const b2Hull * hull, b2Vec2 position, b2Rot rotation, float radius) {
    *result = b2MakeOffsetRoundedPolygon(hull, position, rotation, radius);
}

BOX2D_EXPORT void b2MakeSquare_internal(b2Polygon* result, float halfWidth) {
    *result = b2MakeSquare(halfWidth);
}

BOX2D_EXPORT void b2MakeBox_internal(b2Polygon* result, float halfWidth, float halfHeight) {
    *result = b2MakeBox(halfWidth, halfHeight);
}

BOX2D_EXPORT void b2MakeRoundedBox_internal(b2Polygon* result, float halfWidth, float halfHeight, float radius) {
    *result = b2MakeRoundedBox(halfWidth, halfHeight, radius);
}

BOX2D_EXPORT void b2MakeOffsetBox_internal(b2Polygon* result, float halfWidth, float halfHeight, b2Vec2 center, b2Rot rotation) {
    *result = b2MakeOffsetBox(halfWidth, halfHeight, center, rotation);
}

BOX2D_EXPORT void b2MakeOffsetRoundedBox_internal(b2Polygon* result, float halfWidth, float halfHeight, b2Vec2 center, b2Rot rotation, float radius) {
    *result = b2MakeOffsetRoundedBox(halfWidth, halfHeight, center, rotation, radius);
}

BOX2D_EXPORT void b2TransformPolygon_internal(b2Polygon* result, b2Transform transform, const b2Polygon * polygon) {
    *result = b2TransformPolygon(transform, polygon);
}

BOX2D_EXPORT void b2ComputeCircleMass_internal(b2MassData* result, const b2Circle * shape, float density) {
    *result = b2ComputeCircleMass(shape, density);
}

BOX2D_EXPORT void b2ComputeCapsuleMass_internal(b2MassData* result, const b2Capsule * shape, float density) {
    *result = b2ComputeCapsuleMass(shape, density);
}

BOX2D_EXPORT void b2ComputePolygonMass_internal(b2MassData* result, const b2Polygon * shape, float density) {
    *result = b2ComputePolygonMass(shape, density);
}

BOX2D_EXPORT void b2ComputeCircleAABB_internal(b2AABB* result, const b2Circle * shape, b2Transform transform) {
    *result = b2ComputeCircleAABB(shape, transform);
}

BOX2D_EXPORT void b2ComputeCapsuleAABB_internal(b2AABB* result, const b2Capsule * shape, b2Transform transform) {
    *result = b2ComputeCapsuleAABB(shape, transform);
}

BOX2D_EXPORT void b2ComputePolygonAABB_internal(b2AABB* result, const b2Polygon * shape, b2Transform transform) {
    *result = b2ComputePolygonAABB(shape, transform);
}

BOX2D_EXPORT void b2ComputeSegmentAABB_internal(b2AABB* result, const b2Segment * shape, b2Transform transform) {
    *result = b2ComputeSegmentAABB(shape, transform);
}

BOX2D_EXPORT void b2RayCastCircle_internal(b2CastOutput* result, const b2Circle * shape, const b2RayCastInput * input) {
    *result = b2RayCastCircle(shape, input);
}

BOX2D_EXPORT void b2RayCastCapsule_internal(b2CastOutput* result, const b2Capsule * shape, const b2RayCastInput * input) {
    *result = b2RayCastCapsule(shape, input);
}

BOX2D_EXPORT void b2RayCastSegment_internal(b2CastOutput* result, const b2Segment * shape, const b2RayCastInput * input, bool oneSided) {
    *result = b2RayCastSegment(shape, input, oneSided);
}

BOX2D_EXPORT void b2RayCastPolygon_internal(b2CastOutput* result, const b2Polygon * shape, const b2RayCastInput * input) {
    *result = b2RayCastPolygon(shape, input);
}

BOX2D_EXPORT void b2ShapeCastCircle_internal(b2CastOutput* result, const b2Circle * shape, const b2ShapeCastInput * input) {
    *result = b2ShapeCastCircle(shape, input);
}

BOX2D_EXPORT void b2ShapeCastCapsule_internal(b2CastOutput* result, const b2Capsule * shape, const b2ShapeCastInput * input) {
    *result = b2ShapeCastCapsule(shape, input);
}

BOX2D_EXPORT void b2ShapeCastSegment_internal(b2CastOutput* result, const b2Segment * shape, const b2ShapeCastInput * input) {
    *result = b2ShapeCastSegment(shape, input);
}

BOX2D_EXPORT void b2ShapeCastPolygon_internal(b2CastOutput* result, const b2Polygon * shape, const b2ShapeCastInput * input) {
    *result = b2ShapeCastPolygon(shape, input);
}

BOX2D_EXPORT void b2ComputeHull_internal(b2Hull* result, const b2Vec2 * points, int count) {
    *result = b2ComputeHull(points, count);
}

BOX2D_EXPORT void b2SegmentDistance_internal(b2SegmentDistanceResult* result, b2Vec2 p1, b2Vec2 q1, b2Vec2 p2, b2Vec2 q2) {
    *result = b2SegmentDistance(p1, q1, p2, q2);
}

BOX2D_EXPORT void b2ShapeDistance_internal(b2DistanceOutput* result, const b2DistanceInput * input, b2SimplexCache * cache, b2Simplex * simplexes, int simplexCapacity) {
    *result = b2ShapeDistance(input, cache, simplexes, simplexCapacity);
}

BOX2D_EXPORT void b2ShapeCast_internal(b2CastOutput* result, const b2ShapeCastPairInput * input) {
    *result = b2ShapeCast(input);
}

BOX2D_EXPORT void b2MakeProxy_internal(b2ShapeProxy* result, const b2Vec2 * points, int count, float radius) {
    *result = b2MakeProxy(points, count, radius);
}

BOX2D_EXPORT void b2MakeOffsetProxy_internal(b2ShapeProxy* result, const b2Vec2 * points, int count, float radius, b2Vec2 position, b2Rot rotation) {
    *result = b2MakeOffsetProxy(points, count, radius, position, rotation);
}

BOX2D_EXPORT void b2GetSweepTransform_internal(b2Transform* result, const b2Sweep * sweep, float time) {
    *result = b2GetSweepTransform(sweep, time);
}

BOX2D_EXPORT void b2TimeOfImpact_internal(b2TOIOutput* result, const b2TOIInput * input) {
    *result = b2TimeOfImpact(input);
}

BOX2D_EXPORT void b2CollideCircles_internal(b2Manifold* result, const b2Circle * circleA, b2Transform xfA, const b2Circle * circleB, b2Transform xfB) {
    *result = b2CollideCircles(circleA, xfA, circleB, xfB);
}

BOX2D_EXPORT void b2CollideCapsuleAndCircle_internal(b2Manifold* result, const b2Capsule * capsuleA, b2Transform xfA, const b2Circle * circleB, b2Transform xfB) {
    *result = b2CollideCapsuleAndCircle(capsuleA, xfA, circleB, xfB);
}

BOX2D_EXPORT void b2CollideSegmentAndCircle_internal(b2Manifold* result, const b2Segment * segmentA, b2Transform xfA, const b2Circle * circleB, b2Transform xfB) {
    *result = b2CollideSegmentAndCircle(segmentA, xfA, circleB, xfB);
}

BOX2D_EXPORT void b2CollidePolygonAndCircle_internal(b2Manifold* result, const b2Polygon * polygonA, b2Transform xfA, const b2Circle * circleB, b2Transform xfB) {
    *result = b2CollidePolygonAndCircle(polygonA, xfA, circleB, xfB);
}

BOX2D_EXPORT void b2CollideCapsules_internal(b2Manifold* result, const b2Capsule * capsuleA, b2Transform xfA, const b2Capsule * capsuleB, b2Transform xfB) {
    *result = b2CollideCapsules(capsuleA, xfA, capsuleB, xfB);
}

BOX2D_EXPORT void b2CollideSegmentAndCapsule_internal(b2Manifold* result, const b2Segment * segmentA, b2Transform xfA, const b2Capsule * capsuleB, b2Transform xfB) {
    *result = b2CollideSegmentAndCapsule(segmentA, xfA, capsuleB, xfB);
}

BOX2D_EXPORT void b2CollidePolygonAndCapsule_internal(b2Manifold* result, const b2Polygon * polygonA, b2Transform xfA, const b2Capsule * capsuleB, b2Transform xfB) {
    *result = b2CollidePolygonAndCapsule(polygonA, xfA, capsuleB, xfB);
}

BOX2D_EXPORT void b2CollidePolygons_internal(b2Manifold* result, const b2Polygon * polygonA, b2Transform xfA, const b2Polygon * polygonB, b2Transform xfB) {
    *result = b2CollidePolygons(polygonA, xfA, polygonB, xfB);
}

BOX2D_EXPORT void b2CollideSegmentAndPolygon_internal(b2Manifold* result, const b2Segment * segmentA, b2Transform xfA, const b2Polygon * polygonB, b2Transform xfB) {
    *result = b2CollideSegmentAndPolygon(segmentA, xfA, polygonB, xfB);
}

BOX2D_EXPORT void b2CollideChainSegmentAndCircle_internal(b2Manifold* result, const b2ChainSegment * segmentA, b2Transform xfA, const b2Circle * circleB, b2Transform xfB) {
    *result = b2CollideChainSegmentAndCircle(segmentA, xfA, circleB, xfB);
}

BOX2D_EXPORT void b2CollideChainSegmentAndCapsule_internal(b2Manifold* result, const b2ChainSegment * segmentA, b2Transform xfA, const b2Capsule * capsuleB, b2Transform xfB, b2SimplexCache * cache) {
    *result = b2CollideChainSegmentAndCapsule(segmentA, xfA, capsuleB, xfB, cache);
}

BOX2D_EXPORT void b2CollideChainSegmentAndPolygon_internal(b2Manifold* result, const b2ChainSegment * segmentA, b2Transform xfA, const b2Polygon * polygonB, b2Transform xfB, b2SimplexCache * cache) {
    *result = b2CollideChainSegmentAndPolygon(segmentA, xfA, polygonB, xfB, cache);
}

BOX2D_EXPORT void b2DynamicTree_Create_internal(b2DynamicTree* result) {
    *result = b2DynamicTree_Create();
}

BOX2D_EXPORT void b2DynamicTree_Query_internal(b2TreeStats* result, const b2DynamicTree * tree, b2AABB aabb, uint64_t maskBits, b2TreeQueryCallbackFcn * callback, void * context) {
    *result = b2DynamicTree_Query(tree, aabb, maskBits, callback, context);
}

BOX2D_EXPORT void b2DynamicTree_QueryAll_internal(b2TreeStats* result, const b2DynamicTree * tree, b2AABB aabb, b2TreeQueryCallbackFcn * callback, void * context) {
    *result = b2DynamicTree_QueryAll(tree, aabb, callback, context);
}

BOX2D_EXPORT void b2DynamicTree_RayCast_internal(b2TreeStats* result, const b2DynamicTree * tree, const b2RayCastInput * input, uint64_t maskBits, b2TreeRayCastCallbackFcn * callback, void * context) {
    *result = b2DynamicTree_RayCast(tree, input, maskBits, callback, context);
}

BOX2D_EXPORT void b2DynamicTree_ShapeCast_internal(b2TreeStats* result, const b2DynamicTree * tree, const b2ShapeCastInput * input, uint64_t maskBits, b2TreeShapeCastCallbackFcn * callback, void * context) {
    *result = b2DynamicTree_ShapeCast(tree, input, maskBits, callback, context);
}

BOX2D_EXPORT void b2DynamicTree_GetRootBounds_internal(b2AABB* result, const b2DynamicTree * tree) {
    *result = b2DynamicTree_GetRootBounds(tree);
}

BOX2D_EXPORT void b2DynamicTree_GetAABB_internal(b2AABB* result, const b2DynamicTree * tree, int proxyId) {
    *result = b2DynamicTree_GetAABB(tree, proxyId);
}

BOX2D_EXPORT void b2SolvePlanes_internal(b2PlaneSolverResult* result, b2Vec2 targetDelta, b2CollisionPlane * planes, int count) {
    *result = b2SolvePlanes(targetDelta, planes, count);
}

BOX2D_EXPORT void b2ClipVector_internal(b2Vec2* result, b2Vec2 vector, const b2CollisionPlane * planes, int count) {
    *result = b2ClipVector(vector, planes, count);
}

BOX2D_EXPORT void b2DefaultWorldDef_internal(b2WorldDef* result) {
    *result = b2DefaultWorldDef();
}

BOX2D_EXPORT void b2DefaultBodyDef_internal(b2BodyDef* result) {
    *result = b2DefaultBodyDef();
}

BOX2D_EXPORT void b2DefaultFilter_internal(b2Filter* result) {
    *result = b2DefaultFilter();
}

BOX2D_EXPORT void b2DefaultQueryFilter_internal(b2QueryFilter* result) {
    *result = b2DefaultQueryFilter();
}

BOX2D_EXPORT void b2DefaultSurfaceMaterial_internal(b2SurfaceMaterial* result) {
    *result = b2DefaultSurfaceMaterial();
}

BOX2D_EXPORT void b2DefaultShapeDef_internal(b2ShapeDef* result) {
    *result = b2DefaultShapeDef();
}

BOX2D_EXPORT void b2DefaultChainDef_internal(b2ChainDef* result) {
    *result = b2DefaultChainDef();
}

BOX2D_EXPORT void b2DefaultDistanceJointDef_internal(b2DistanceJointDef* result) {
    *result = b2DefaultDistanceJointDef();
}

BOX2D_EXPORT void b2DefaultMotorJointDef_internal(b2MotorJointDef* result) {
    *result = b2DefaultMotorJointDef();
}

BOX2D_EXPORT void b2DefaultFilterJointDef_internal(b2FilterJointDef* result) {
    *result = b2DefaultFilterJointDef();
}

BOX2D_EXPORT void b2DefaultPrismaticJointDef_internal(b2PrismaticJointDef* result) {
    *result = b2DefaultPrismaticJointDef();
}

BOX2D_EXPORT void b2DefaultRevoluteJointDef_internal(b2RevoluteJointDef* result) {
    *result = b2DefaultRevoluteJointDef();
}

BOX2D_EXPORT void b2DefaultWeldJointDef_internal(b2WeldJointDef* result) {
    *result = b2DefaultWeldJointDef();
}

BOX2D_EXPORT void b2DefaultWheelJointDef_internal(b2WheelJointDef* result) {
    *result = b2DefaultWheelJointDef();
}

BOX2D_EXPORT void b2DefaultExplosionDef_internal(b2ExplosionDef* result) {
    *result = b2DefaultExplosionDef();
}

BOX2D_EXPORT void b2DefaultDebugDraw_internal(b2DebugDraw* result) {
    *result = b2DefaultDebugDraw();
}

BOX2D_EXPORT void b2CreateWorld_internal(b2WorldId* result, const b2WorldDef * def) {
    *result = b2CreateWorld(def);
}

BOX2D_EXPORT void b2World_GetBodyEvents_internal(b2BodyEvents* result, b2WorldId worldId) {
    *result = b2World_GetBodyEvents(worldId);
}

BOX2D_EXPORT void b2World_GetSensorEvents_internal(b2SensorEvents* result, b2WorldId worldId) {
    *result = b2World_GetSensorEvents(worldId);
}

BOX2D_EXPORT void b2World_GetContactEvents_internal(b2ContactEvents* result, b2WorldId worldId) {
    *result = b2World_GetContactEvents(worldId);
}

BOX2D_EXPORT void b2World_GetJointEvents_internal(b2JointEvents* result, b2WorldId worldId) {
    *result = b2World_GetJointEvents(worldId);
}

BOX2D_EXPORT void b2World_OverlapAABB_internal(b2TreeStats* result, b2WorldId worldId, b2AABB aabb, b2QueryFilter filter, b2OverlapResultFcn * fcn, void * context) {
    *result = b2World_OverlapAABB(worldId, aabb, filter, fcn, context);
}

BOX2D_EXPORT void b2World_OverlapShape_internal(b2TreeStats* result, b2WorldId worldId, const b2ShapeProxy * proxy, b2QueryFilter filter, b2OverlapResultFcn * fcn, void * context) {
    *result = b2World_OverlapShape(worldId, proxy, filter, fcn, context);
}

BOX2D_EXPORT void b2World_CastRay_internal(b2TreeStats* result, b2WorldId worldId, b2Vec2 origin, b2Vec2 translation, b2QueryFilter filter, b2CastResultFcn * fcn, void * context) {
    *result = b2World_CastRay(worldId, origin, translation, filter, fcn, context);
}

BOX2D_EXPORT void b2World_CastRayClosest_internal(b2RayResult* result, b2WorldId worldId, b2Vec2 origin, b2Vec2 translation, b2QueryFilter filter) {
    *result = b2World_CastRayClosest(worldId, origin, translation, filter);
}

BOX2D_EXPORT void b2World_CastShape_internal(b2TreeStats* result, b2WorldId worldId, const b2ShapeProxy * proxy, b2Vec2 translation, b2QueryFilter filter, b2CastResultFcn * fcn, void * context) {
    *result = b2World_CastShape(worldId, proxy, translation, filter, fcn, context);
}

BOX2D_EXPORT void b2World_GetGravity_internal(b2Vec2* result, b2WorldId worldId) {
    *result = b2World_GetGravity(worldId);
}

BOX2D_EXPORT void b2World_GetProfile_internal(b2Profile* result, b2WorldId worldId) {
    *result = b2World_GetProfile(worldId);
}

BOX2D_EXPORT void b2World_GetCounters_internal(b2Counters* result, b2WorldId worldId) {
    *result = b2World_GetCounters(worldId);
}

BOX2D_EXPORT void b2CreateBody_internal(b2BodyId* result, b2WorldId worldId, const b2BodyDef * def) {
    *result = b2CreateBody(worldId, def);
}

BOX2D_EXPORT void b2Body_GetPosition_internal(b2Vec2* result, b2BodyId bodyId) {
    *result = b2Body_GetPosition(bodyId);
}

BOX2D_EXPORT void b2Body_GetRotation_internal(b2Rot* result, b2BodyId bodyId) {
    *result = b2Body_GetRotation(bodyId);
}

BOX2D_EXPORT void b2Body_GetTransform_internal(b2Transform* result, b2BodyId bodyId) {
    *result = b2Body_GetTransform(bodyId);
}

BOX2D_EXPORT void b2Body_GetLocalPoint_internal(b2Vec2* result, b2BodyId bodyId, b2Vec2 worldPoint) {
    *result = b2Body_GetLocalPoint(bodyId, worldPoint);
}

BOX2D_EXPORT void b2Body_GetWorldPoint_internal(b2Vec2* result, b2BodyId bodyId, b2Vec2 localPoint) {
    *result = b2Body_GetWorldPoint(bodyId, localPoint);
}

BOX2D_EXPORT void b2Body_GetLocalVector_internal(b2Vec2* result, b2BodyId bodyId, b2Vec2 worldVector) {
    *result = b2Body_GetLocalVector(bodyId, worldVector);
}

BOX2D_EXPORT void b2Body_GetWorldVector_internal(b2Vec2* result, b2BodyId bodyId, b2Vec2 localVector) {
    *result = b2Body_GetWorldVector(bodyId, localVector);
}

BOX2D_EXPORT void b2Body_GetLinearVelocity_internal(b2Vec2* result, b2BodyId bodyId) {
    *result = b2Body_GetLinearVelocity(bodyId);
}

BOX2D_EXPORT void b2Body_GetLocalPointVelocity_internal(b2Vec2* result, b2BodyId bodyId, b2Vec2 localPoint) {
    *result = b2Body_GetLocalPointVelocity(bodyId, localPoint);
}

BOX2D_EXPORT void b2Body_GetWorldPointVelocity_internal(b2Vec2* result, b2BodyId bodyId, b2Vec2 worldPoint) {
    *result = b2Body_GetWorldPointVelocity(bodyId, worldPoint);
}

BOX2D_EXPORT void b2Body_GetLocalCenterOfMass_internal(b2Vec2* result, b2BodyId bodyId) {
    *result = b2Body_GetLocalCenterOfMass(bodyId);
}

BOX2D_EXPORT void b2Body_GetWorldCenterOfMass_internal(b2Vec2* result, b2BodyId bodyId) {
    *result = b2Body_GetWorldCenterOfMass(bodyId);
}

BOX2D_EXPORT void b2Body_GetMassData_internal(b2MassData* result, b2BodyId bodyId) {
    *result = b2Body_GetMassData(bodyId);
}

BOX2D_EXPORT void b2Body_GetMotionLocks_internal(b2MotionLocks* result, b2BodyId bodyId) {
    *result = b2Body_GetMotionLocks(bodyId);
}

BOX2D_EXPORT void b2Body_GetWorld_internal(b2WorldId* result, b2BodyId bodyId) {
    *result = b2Body_GetWorld(bodyId);
}

BOX2D_EXPORT void b2Body_ComputeAABB_internal(b2AABB* result, b2BodyId bodyId) {
    *result = b2Body_ComputeAABB(bodyId);
}

BOX2D_EXPORT void b2CreateCircleShape_internal(b2ShapeId* result, b2BodyId bodyId, const b2ShapeDef * def, const b2Circle * circle) {
    *result = b2CreateCircleShape(bodyId, def, circle);
}

BOX2D_EXPORT void b2CreateSegmentShape_internal(b2ShapeId* result, b2BodyId bodyId, const b2ShapeDef * def, const b2Segment * segment) {
    *result = b2CreateSegmentShape(bodyId, def, segment);
}

BOX2D_EXPORT void b2CreateCapsuleShape_internal(b2ShapeId* result, b2BodyId bodyId, const b2ShapeDef * def, const b2Capsule * capsule) {
    *result = b2CreateCapsuleShape(bodyId, def, capsule);
}

BOX2D_EXPORT void b2CreatePolygonShape_internal(b2ShapeId* result, b2BodyId bodyId, const b2ShapeDef * def, const b2Polygon * polygon) {
    *result = b2CreatePolygonShape(bodyId, def, polygon);
}

BOX2D_EXPORT void b2Shape_GetBody_internal(b2BodyId* result, b2ShapeId shapeId) {
    *result = b2Shape_GetBody(shapeId);
}

BOX2D_EXPORT void b2Shape_GetWorld_internal(b2WorldId* result, b2ShapeId shapeId) {
    *result = b2Shape_GetWorld(shapeId);
}

BOX2D_EXPORT void b2Shape_GetSurfaceMaterial_internal(b2SurfaceMaterial* result, b2ShapeId shapeId) {
    *result = b2Shape_GetSurfaceMaterial(shapeId);
}

BOX2D_EXPORT void b2Shape_GetFilter_internal(b2Filter* result, b2ShapeId shapeId) {
    *result = b2Shape_GetFilter(shapeId);
}

BOX2D_EXPORT void b2Shape_RayCast_internal(b2CastOutput* result, b2ShapeId shapeId, const b2RayCastInput * input) {
    *result = b2Shape_RayCast(shapeId, input);
}

BOX2D_EXPORT void b2Shape_GetCircle_internal(b2Circle* result, b2ShapeId shapeId) {
    *result = b2Shape_GetCircle(shapeId);
}

BOX2D_EXPORT void b2Shape_GetSegment_internal(b2Segment* result, b2ShapeId shapeId) {
    *result = b2Shape_GetSegment(shapeId);
}

BOX2D_EXPORT void b2Shape_GetChainSegment_internal(b2ChainSegment* result, b2ShapeId shapeId) {
    *result = b2Shape_GetChainSegment(shapeId);
}

BOX2D_EXPORT void b2Shape_GetCapsule_internal(b2Capsule* result, b2ShapeId shapeId) {
    *result = b2Shape_GetCapsule(shapeId);
}

BOX2D_EXPORT void b2Shape_GetPolygon_internal(b2Polygon* result, b2ShapeId shapeId) {
    *result = b2Shape_GetPolygon(shapeId);
}

BOX2D_EXPORT void b2Shape_GetParentChain_internal(b2ChainId* result, b2ShapeId shapeId) {
    *result = b2Shape_GetParentChain(shapeId);
}

BOX2D_EXPORT void b2Shape_GetAABB_internal(b2AABB* result, b2ShapeId shapeId) {
    *result = b2Shape_GetAABB(shapeId);
}

BOX2D_EXPORT void b2Shape_ComputeMassData_internal(b2MassData* result, b2ShapeId shapeId) {
    *result = b2Shape_ComputeMassData(shapeId);
}

BOX2D_EXPORT void b2Shape_GetClosestPoint_internal(b2Vec2* result, b2ShapeId shapeId, b2Vec2 target) {
    *result = b2Shape_GetClosestPoint(shapeId, target);
}

BOX2D_EXPORT void b2CreateChain_internal(b2ChainId* result, b2BodyId bodyId, const b2ChainDef * def) {
    *result = b2CreateChain(bodyId, def);
}

BOX2D_EXPORT void b2Chain_GetWorld_internal(b2WorldId* result, b2ChainId chainId) {
    *result = b2Chain_GetWorld(chainId);
}

BOX2D_EXPORT void b2Chain_GetSurfaceMaterial_internal(b2SurfaceMaterial* result, b2ChainId chainId, int materialIndex) {
    *result = b2Chain_GetSurfaceMaterial(chainId, materialIndex);
}

BOX2D_EXPORT void b2Joint_GetBodyA_internal(b2BodyId* result, b2JointId jointId) {
    *result = b2Joint_GetBodyA(jointId);
}

BOX2D_EXPORT void b2Joint_GetBodyB_internal(b2BodyId* result, b2JointId jointId) {
    *result = b2Joint_GetBodyB(jointId);
}

BOX2D_EXPORT void b2Joint_GetWorld_internal(b2WorldId* result, b2JointId jointId) {
    *result = b2Joint_GetWorld(jointId);
}

BOX2D_EXPORT void b2Joint_GetLocalFrameA_internal(b2Transform* result, b2JointId jointId) {
    *result = b2Joint_GetLocalFrameA(jointId);
}

BOX2D_EXPORT void b2Joint_GetLocalFrameB_internal(b2Transform* result, b2JointId jointId) {
    *result = b2Joint_GetLocalFrameB(jointId);
}

BOX2D_EXPORT void b2Joint_GetConstraintForce_internal(b2Vec2* result, b2JointId jointId) {
    *result = b2Joint_GetConstraintForce(jointId);
}

BOX2D_EXPORT void b2CreateDistanceJoint_internal(b2JointId* result, b2WorldId worldId, const b2DistanceJointDef * def) {
    *result = b2CreateDistanceJoint(worldId, def);
}

BOX2D_EXPORT void b2CreateMotorJoint_internal(b2JointId* result, b2WorldId worldId, const b2MotorJointDef * def) {
    *result = b2CreateMotorJoint(worldId, def);
}

BOX2D_EXPORT void b2MotorJoint_GetLinearVelocity_internal(b2Vec2* result, b2JointId jointId) {
    *result = b2MotorJoint_GetLinearVelocity(jointId);
}

BOX2D_EXPORT void b2CreateFilterJoint_internal(b2JointId* result, b2WorldId worldId, const b2FilterJointDef * def) {
    *result = b2CreateFilterJoint(worldId, def);
}

BOX2D_EXPORT void b2CreatePrismaticJoint_internal(b2JointId* result, b2WorldId worldId, const b2PrismaticJointDef * def) {
    *result = b2CreatePrismaticJoint(worldId, def);
}

BOX2D_EXPORT void b2CreateRevoluteJoint_internal(b2JointId* result, b2WorldId worldId, const b2RevoluteJointDef * def) {
    *result = b2CreateRevoluteJoint(worldId, def);
}

BOX2D_EXPORT void b2CreateWeldJoint_internal(b2JointId* result, b2WorldId worldId, const b2WeldJointDef * def) {
    *result = b2CreateWeldJoint(worldId, def);
}

BOX2D_EXPORT void b2CreateWheelJoint_internal(b2JointId* result, b2WorldId worldId, const b2WheelJointDef * def) {
    *result = b2CreateWheelJoint(worldId, def);
}

BOX2D_EXPORT void b2Contact_GetData_internal(b2ContactData* result, b2ContactId contactId) {
    *result = b2Contact_GetData(contactId);
}

#endif // BOX2D_CSHARP_INTERNAL_WRAPPERS_H
