/******************************************************************************
 * Box2D C# Extension Implementation
 * 
 * This file includes the Box2D headers and the auto-generated C# binding
 * internal wrapper functions for WebAssembly/Emscripten support.
 *****************************************************************************/

/* Include Box2D headers */
#include <box2d/box2d.h>
#include <box2d/math_functions.h>

/*=== C# BINDING HELPERS =====================================================
    WebAssembly/Emscripten cannot marshal structs returned by value through P/Invoke.
    These _internal helper functions work around this limitation by taking an output
    pointer parameter instead. The C# binding generator automatically creates wrappers
    that call these functions on WebAssembly builds while using the regular functions
    on other platforms.
    
    The internal wrapper functions are auto-generated by bindgen/gen_csharp.py
    and included from box2d_csharp_internal_wrappers.h
============================================================================*/

// Include auto-generated internal wrapper functions for Box2D C# bindings
#include "../box2d_csharp_internal_wrappers.h"
